---
- name: add user
  become: true
  hosts: all
  vars_files:
    - users.yml
  tasks:
    - name: create file
      debug:
        msg: "{{ lookup('password','/tmp/'+item.key+'.file length=10')}}"
      with_dict: "{{ users }}"
    - name: create user
      user: 
        name: "{{ item.key }}"
        comment: "{{ item.value.f | title }} {{ item.value.m[0] | title }} {{ item.value.l | title }}"
        password: "{{ lookup('file','/tmp/'+item.key+'.file ) | password_hash('sha512')}}"
      with_dict: "{{ users }}"
