---
- hosts: webservers
  become: true
  tasks:
    - yum:
        name: httpd
    - systemd:
        name: httpd
        state: started
    - name: Transfer to http
      copy:
        src: package.tgz
        dest: /var/www/html/package.tgz
        remote_src: no
    - shell: 'echo -e "---\nchecksum:" `sha256sum package.tgz | cut -f1 -d" "` >  integrity.yml'
      delegate_to: localhost
      become_user: cloud_user
